### ISSUE TITLE
Tentative: Find a better algorithm to use for text-emotional analysis

### ISSUE THREAD

**Issue by heatherzhu** [meganminnear/0351MachineLearners#26]
Our current algorithm for text-emotional analysis is Naïve Bayes, which currently works decently well for us. However, if we can find a better algorithm to use, it would be preferable.

**Comment by heatherzhu** [comment]
DeepMoji Python3 found and will be tried out.

**Comment by ShaanGil1** [comment]
Currently working with Python3 DeepMoji
